name = "JuliaBLAS"
uuid = "ae1e96b1-5176-43ee-a525-f61fd659fa53"
authors = ["Yingbo Ma <mayingbo5@gmail.com>"]
version = "0.1.0"

[deps]
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
